name: CI

on:
  push:
    branches:
      - main
      - master
      # bors needs CI to trigger for pushes to its staging/trying branches
      - staging
      - trying
  pull_request:

env:
  RUSTFLAGS: -Cdebuginfo=0
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: 1

jobs:
  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.toolchain == 'nightly' }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        toolchain: [stable, beta, nightly]
    steps:
      - uses: actions/checkout@v2

      - name: install ${{ matrix.toolchain }} toolchain
        id: install_toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
          override: true

      - run: CFG_RELEASE_CHANNEL="nightly" CFG_RELEASE="nightly" cargo +nightly install --force rustfmt-nightly --git https://github.com/rust-lang/rustfmt --tag v1.4.35 --all-features
        if: matrix.toolchain == 'nightly' && matrix.os == 'ubuntu-latest'

      - run: cargo +nightly fmt --all -- --check
        if: matrix.toolchain == 'nightly' && matrix.os == 'ubuntu-latest'
        
      - run: rustup component add clippy
        if: matrix.toolchain == 'nightly'

      - run: cargo +nightly clippy -Z unstable-options --workspace --all-targets --all-features
        if: matrix.toolchain == 'nightly'

      - run: cargo install cargo-hack
      - run: cargo hack test --workspace --each-feature

      - uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'
        if: matrix.toolchain == 'stable' && matrix.os == 'ubuntu-latest'

      - run: cargo install mdbook-linkcheck
        if: matrix.toolchain == 'stable' && matrix.os == 'ubuntu-latest'

      - run: mdbook build docs/book
        if: matrix.toolchain == 'stable' && matrix.os == 'ubuntu-latest'

      - run: mdbook test -L ./target/debug/deps docs/book
        if: matrix.toolchain == 'stable' && matrix.os == 'ubuntu-latest'
